# task
task: GraphLSurv # GraphPredict
experiment_type: sim # std-hpopt std-perfm
random_state: 42

# output
save_path: ./results-hyopt/NLST/GraphLSurv-Default

# spliting
seed_split: [29, 44, 46, 55, 86]
data_split: ./data_split/nlst/nlst-seed{}.npz

# data
dataset_name: nlst
dir_sld_feat: /home/liup/data/NLST/feats-l1-s256-mrandom_be-n1000-color_norm/h5_files
dir_pat_graph: /home/liup/data/NLST/feats-l1-s256-mrandom_be-n1000-color_norm/graph-knn-k10-t0
path_csv: /home/liup/data/NLST/nlst_path_full.csv
undirect_graph: True
split_stratify: False
save_prediction: True

# training
batch_size: 1
num_workers: 8
optimizer_type: adam
lr: 0.0002
weight_decay: 0.0005
lr_factor: 0.5
lr_patience: 5
lr_min: 0.00001
epochs: 200
bp_every_iters: 32
patience: 5

# graph_learn_regularization
graph_reg: True
smoothness_ratio: 0.1
degree_ratio: 0.001
sparsity_ratio: 0.001

# model
model_in_dim: 1024
model_hid_dim: 128
model_out_dim: 1
model_num_layers: 1
model_dropout_ratio: 0.6

# loss
loss_type: sim-breslow
reg_l1: 0.00001

# anchor graph learner layer
agl_hid_dim: 128
agl_ratio_anchors: [0.05, 0.1, 0.2]
agl_epsilon: [0.7, 0.8, 0.9]
agl_topk: null
agl_metric_type: transformer

# anchor graph encoder layer
age_graph_hops: [1, 2, 3]
age_ratio_init_graph: [0, 0.1, 0.2, 0.5, 1.0]
age_dropout_ratio: 0.6
age_batch_norm: False

# device
no_cuda: False
cuda_id: 1
